environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cargo install mdbook --vers '0.0.22' --debug

build: false

test_script:
  - cargo test
  - mdbook build
